version: "3.7"

networks:
  spendmanagement:
    name: spendmanagement-network

services:
    jaeger:
      image: jaegertracing/all-in-one
      container_name: jaeger
      restart: unless-stopped
      environment:
        - COLLECTOR_ZIPKIN_HOST_PORT=:9411
        - COLLECTOR_OTLP_ENABLED=true
      ports:
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 4317:4317
        - 4318:4318
        - 14250:14250
        - 14268:14268
        - 14269:14269
      networks:
        - spendmanagement
    
    sqlserver:
      container_name: sqlserver
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - "1433:1433"
      networks:
        - spendmanagement
      environment:
        SA_PASSWORD: "SqlServer2019!"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
      volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup

    mongo:
      image: mongo
      container_name: mongo
      ports:
          - 27017:27017
      networks:
        - spendmanagement
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root

    zookeeper:
      image: 'zookeeper:3.4.13'
      container_name: zookeeper
      ports:
        - '2181:2181'
      networks:
        - spendmanagement
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

    kafka-spendmanagement:
      image: 'wurstmeister/kafka:2.13-2.7.0'
      container_name: kafka-spendmanagement
      ports:
        - 9092:9092
        - 9094:9094
      networks:
        - spendmanagement
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
        KAFKA_LISTENERS: OUTSIDE://:9094,INSIDE://:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      depends_on:
        - zookeeper


volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
  